databases:
  - name: bodytrackpro
    databaseName: bodytrackpro
    user: bodytrackpro

services:
  - type: web
    name: bodytrackpro
    runtime: ruby #or env instead of runtime
    buildCommand: "./bin/render-build.sh"
    startCommand: "./bin/render-start.sh"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bodytrackpro
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false